### PR TITLE
adding sandbox end point for testmode

### PR DESCRIPTION
**Pull request by Webvida**
Resolve issue #6

### CODE REVIEW

**Comment by Webvida** [comment]
Something messed up with this :( Redoing

**Comment by kayladnls** [comment]
I'll leave this open while you fix, no worries. Can you squash when you're done, and ping me when it's ready? Thank you!

**Comment by outrunthewolf** [comment]
This functionality would be very helpful for us. Are you still planning to complete it?

**Comment by mikenolimits** [comment]
Could this get merged in? I tested it locally and it appears to work.

**Comment by laoneo** [comment]
Any plans to merge this?

**Comment by outrunthewolf** [comment]
Can't merge if it doesn't pass its tests @Webvida @mikenolimits

**Comment by delatbabel** [comment]
I believe that this is now superfluous because of #11

**Pull request closed without merging**
